import { PrislistaRow } from "@/types/Prislista.types";

const AVAILABLE = {
    value: "available",
    label: "Tillgänglig",
    order: 0,
} as const;
const RESERVED = {
    value: "reserved",
    label: "Reserverad",
    order: 1,
} as const;
const SOLD = { value: "sold", label: "Såld", order: 2 } as const;

export const prislistaData: PrislistaRow[] = [
    {
        id: "bostad-1",
        name: "Bostad 1",
        status: SOLD,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "Såld",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-2",
        name: "Bostad 2",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "17 995 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-3",
        name: "Bostad 3",
        status: RESERVED,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "17 495 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-4",
        name: "Bostad 4",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "16 995 999 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-5",
        name: "Bostad 5",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "18 495 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-6",
        name: "Bostad 6",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "18 995 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-7",
        name: "Bostad 7",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "19 395 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-8",
        name: "Bostad 8",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "19 895 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-9",
        name: "Bostad 9",
        status: AVAILABLE,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "19 495 000 kr",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
    {
        id: "bostad-10",
        name: "Bostad 10",
        status: SOLD,
        type: "Parhus",
        rooms: "5 rum & kök",
        livingArea: "173 kvm",
        otherArea: "67 kvm",
        price: "Såld",
        fee: "6 998 kr",
        factSheetUrl: "#",
        interestUrl: "#",
    },
];
